{"name": "test_zero_division", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'maximum 111' in 'maximum recursion depth exceeded'\n +  where 'maximum recursion depth exceeded' = str(RecursionError('maximum recursion depth exceeded'))\n +    where RecursionError('maximum recursion depth exceeded') = <ExceptionInfo RecursionError tblen=960>.value", "trace": "self = <testcases.api_test.agent.test_agent.Test_agent object at 0x00000000040765B0>\n\n    def test_zero_division(self):\n        with pytest.raises(RuntimeError) as excinfo:\n            def f():\n                f()\n            f()\n>       assert 'maximum 111' in str(excinfo.value)\nE       AssertionError: assert 'maximum 111' in 'maximum recursion depth exceeded'\nE        +  where 'maximum recursion depth exceeded' = str(RecursionError('maximum recursion depth exceeded'))\nE        +    where RecursionError('maximum recursion depth exceeded') = <ExceptionInfo RecursionError tblen=960>.value\n\ntestcases\\api_test\\agent\\test_agent.py:29: AssertionError"}, "start": 1709107939303, "stop": 1709107939309, "uuid": "b0c5522c-04c6-4204-9287-2fd975b5417f", "historyId": "c900ed9ecae374607bebf2aca66bcff3", "testCaseId": "71a0be7b9936cba99a5d0446ad76afc6", "fullName": "testcases.api_test.agent.test_agent.Test_agent#test_zero_division", "labels": [{"name": "feature", "value": "获取agent模块接口"}, {"name": "epic", "value": "测试"}, {"name": "parentSuite", "value": "testcases.api_test.agent"}, {"name": "suite", "value": "test_agent"}, {"name": "subSuite", "value": "Test_agent"}, {"name": "host", "value": "SKY-20151030HPK"}, {"name": "thread", "value": "3764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.agent.test_agent"}]}